# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('right', models.IntegerField()),
                ('username', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='worksDTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=64)),
                ('StartDate', models.CharField(max_length=32)),
                ('EstimateDate', models.CharField(max_length=32)),
                ('DoneDate', models.CharField(max_length=32, null=True)),
                ('Status', models.CharField(max_length=16, null=True)),
                ('Notes', models.CharField(max_length=500, null=True)),
                ('Reasons', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='worksRelationDTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('work_id', models.IntegerField()),
                ('work_status', models.CharField(max_length=32)),
            ],
        ),
    ]
